//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: hello.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import Dispatch
import SwiftGRPC
import SwiftProtobuf

internal protocol Hello_HelloServiceSayHelloCall: ClientCallUnary {}

fileprivate final class Hello_HelloServiceSayHelloCallBase: ClientCallUnaryBase<Hello_HelloRequest, Hello_HelloResponse>, Hello_HelloServiceSayHelloCall {
  override class var method: String { return "/hello.HelloService/SayHello" }
}


/// Instantiate Hello_HelloServiceServiceClient, then call methods of this protocol to make API calls.
internal protocol Hello_HelloServiceService: ServiceClient {
  /// Synchronous. Unary.
  func sayHello(_ request: Hello_HelloRequest) throws -> Hello_HelloResponse
  /// Asynchronous. Unary.
  func sayHello(_ request: Hello_HelloRequest, completion: @escaping (Hello_HelloResponse?, CallResult) -> Void) throws -> Hello_HelloServiceSayHelloCall

}

internal final class Hello_HelloServiceServiceClient: ServiceClientBase, Hello_HelloServiceService {
  /// Synchronous. Unary.
  internal func sayHello(_ request: Hello_HelloRequest) throws -> Hello_HelloResponse {
    return try Hello_HelloServiceSayHelloCallBase(channel)
      .run(request: request, metadata: metadata)
  }
  /// Asynchronous. Unary.
  internal func sayHello(_ request: Hello_HelloRequest, completion: @escaping (Hello_HelloResponse?, CallResult) -> Void) throws -> Hello_HelloServiceSayHelloCall {
    return try Hello_HelloServiceSayHelloCallBase(channel)
      .start(request: request, metadata: metadata, completion: completion)
  }

}

